connect to mongodb,create database,collections and documents
africacodeacademy/team-social-quiz-backend pull request #4
Opened 2021-09-23 13:12 UTC by bulaneNayo

2021-10-03 17:15 UTC, eliasbayona requested changes

2021-10-03 17:15 UTC, eliasbayona commented on models/Question.js
> +      unique: true,
unique constraint not necessary

2021-10-03 17:15 UTC, eliasbayona commented on models/Game.js
> +      ref: "users",
Invalid ref, Ref are Case sensitive

2021-10-03 17:15 UTC, eliasbayona commented on models/Leaderboard.js
> +    winning_score:{
rename this to game if it is a ref to a game

2021-10-03 17:15 UTC, eliasbayona commented on models/User.js
> +      type: Boolean,
invalid type, game_history should host a list of all games that the user has played

2021-10-04 10:04 UTC, bulaneNayo commented on models/Leaderboard.js
> +    winning_score:{
i don't understand Elias, what exactly should i rename to game?

2021-10-10 10:59 UTC, merged