fixing create quiz debug
africacodeacademy/team-social-quiz-backend pull request #44
Opened 2021-10-29 08:07 UTC by Mosuhli-Coder

2021-11-01 14:56 UTC, eliasbayona requested changes

2021-11-01 14:56 UTC, eliasbayona commented on controllers/quiz.js
> +    if (!await quizUtils.doesQuizExist(title) && category == new ObjectId(category)) {
use =>  ObjectId.isValid(caregory)

2021-11-02 09:37 UTC, Mosuhli-Coder commented on controllers/quiz.js
> +    if (!await quizUtils.doesQuizExist(title) && category == new ObjectId(category)) {
Please check, i have applied the changes

2021-11-11 21:29 UTC, eliasbayona approved these changes

2021-11-11 21:29 UTC, merged