Feature #### signup bug fixes
africacodeacademy/team-social-quiz-backend pull request #49
Opened 2021-11-02 13:47 UTC by Mosuhli-Coder

2021-11-02 14:51 UTC, eliasbayona requested changes

2021-11-02 14:51 UTC, eliasbayona commented on controllers/authentication.js
> +        return res.send("Please fill out all the fields")
return appropriate server status code

2021-11-02 14:51 UTC, eliasbayona commented on controllers/authentication.js
> +        return res.send("Please fill out all the fields")
return appropriate respond status code

2021-11-02 14:51 UTC, eliasbayona commented on routes/login.js
> +          "profile.name.screenName":username,
screen names are not unique, use email instead

2021-11-02 14:51 UTC, eliasbayona commented on routes/login.js
> +           password: password
not sure why you moved the previous block of code, at the current moment you cannot compare a hashed password string with a plain text password string

2021-11-02 15:33 UTC, Mosuhli-Coder commented on routes/login.js
> +           password: password
The problem is admin is the one whose password is stored and the password its just plain, i don't know what i have to do, please help

2021-11-03 08:20 UTC, eliasbayona requested changes

2021-11-03 08:20 UTC, eliasbayona commented on controllers/authentication.js
> +        if(password === confirmPassword){
take another look at the flow of your logic here.

You seem to be creating an admin user before you actually check if the preconditions to create the user pass.
i.e you generally want to do all the password checks before creating the user.

2021-11-03 08:40 UTC, Mosuhli-Coder commented on controllers/authentication.js
> +        if(password === confirmPassword){
Meaning i should check if the password matches, if not, i should not send data,  else send data, i don't understand

2021-11-04 14:41 UTC, merged